### ISSUE TITLE
cjq_parse() shouldn't recompile source program

### ISSUE THREAD

**Issue by jdroob** [jdroob/cjq#10]
Or for that matter, even take the source program as input. The execution phase should only accept display option flags and paths to JSON data as command-line arguments.

**Comment by JohnDRubio** [comment]
Currently planning to implement a serialization-deserialization solution to resolve this issue. Will start on this as soon as I'm through testing.

**Comment by jdroob** [comment]
Able to avoid recompilation by deserializing jq->bc from tracing stage!
